### ISSUE TITLE
Toggle playing song from playlist?

### ISSUE THREAD

**Issue by Catsvilles** [rudywaltz/tilos-client#43]
Hi, I'm using this repo as a starting, learning base for building an advanced audio player with Svelte/Sapper (trying to learn those). At the moment I stuck on the problem of trying to implement PLAY/PAUSE button for every episode. I tried to set a new song in the store in Episode.svelte, then I also tried to import and run loadNewSong() from Player.svelte but that didn't work and seem to be a wrong approach. I cannot wrap my head around this and find the best solution how to start song outside Player.svelte component, maybe you have some better ideas and directions about this? Thank you!

**Comment by rudywaltz** [comment]
Hi @Catsvilles,
really sorry, I didn't saw your request, do you have still this issue?

Best,
David

**Comment by Catsvilles** [comment]
@rudywaltz Hey, thanks for getting back to me! Yes, I do! I paused the whole project until now, to do something else and learn Sapper better but still I kinda cannot wrap my head around it on how could I do it better using the Svelte's reactivity and store or exporting loadNewSong() to playlist (seems like very hardcoded solution) if you have an idea and example on best/simple way to do it I will be very thankful to hear it out! Thanks :)

**Comment by rudywaltz** [comment]
Hi,
after reviewing my code, I recognize a lot of mixture of the local and global state (I hope one day I can simplify) but here one solution.

I put the currently played song in the store, so you can have access from another component as well.
The player component has responsibility handling the start/play etc.
You can subscribe to the store (song) change in Player, and decide what do you want to do.
- maybe you need to stop the currently played song `currentSound.unload();`
- load the new `currentSound = createCurrentSong()`
- and start playing `playSound()`

here the full diff:

```diff
diff --git a/src/components/Episode.svelte b/src/components/Episode.svelte
index 278fde6..5e9a433 100644
--- a/src/components/Episode.svelte
+++ b/src/components/Episode.svelte
@@ -30,6 +30,14 @@
     }];
   };
 
+  const playNow = () => {
+    $song = {
+      title: name,
+      url: mp3,
+      duration: duration
+    }
+  }
+
   const hideArtist = () => {
     $hiddenShows = [...$hiddenShows, showId];
   };
@@ -61,6 +69,8 @@
     <p class="episode__diary">{text}</p>
     <code class="episode__link">{mp3}</code>
     <br>
+    <button type="button" on:click="{playNow}">Play Now</button>
+    <br>
     <button type="button" on:click={playlistToggle} class="episode__add_playlist" disabled={!inThePast}>{isInPlaylist ? 'Remove from Playlist' : 'Add to Playlist'}</button>
     <br>
     <button type="button" on:click={hideArtist} class="episode__hide_artist">Hide this Artist</button>
diff --git a/src/components/Player.svelte b/src/components/Player.svelte
index 3d7e254..977b034 100644
--- a/src/components/Player.svelte
+++ b/src/components/Player.svelte
@@ -13,6 +13,7 @@
   let currentSound = null;
   let showVolumeBar = false;
   let unsubscribe = () => { };
+  let unscribeSong = () => { };
 
   $: percent = (time / duration * 100).toFixed(2) || 0;
 
@@ -25,12 +26,23 @@
       currentSound = createCurrentSong();
     });
 
+    unscribeSong = song.subscribe((song) => {
+      if (currentSound) {
+        currentSound.unload();
+      }
+      currentSound = createCurrentSong();
+      playSound()
+    })
+
     Howler.volume(volume);
     loadNewSong();
     currentSound = createCurrentSong();
   });
 
-  onDestroy(unsubscribe);
+  onDestroy(() => {
+    unsubscribe();
+    unscribeSong();
+  });
 
   const createCurrentSong = () => {
     const playing1 = playing;


```

**Comment by Catsvilles** [comment]
@rudywaltz Thank you very much! It works very well! Yeah, I'm not much experienced with Svelte/Sapper but from my glance - the global states and reactivity look quite complicated, I hope this doesn't actually effect the performance of the web app, in any case there is always room for improvements. :) Cheers!
